=== qubegubble/blockwoche/xml-content/database/database.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="energie-data">
        <xs:complexType>
            <xs:all>
                <xs:element ref="energie-plant" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="energie-plant">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="plant" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="plant">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element ref="offer" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="offer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="postalcode" type="xs:int" minOccurs="1" maxOccurs="1" />
                <xs:element name="price" type="xs:decimal" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="date" type="xs:date" />
        </xs:complexType>
    </xs:element>

</xs:schema>

=== qubegubble/blockwoche/xml-content/database/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<energie-data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="database.xsd">
    <energie-plant>
        <plant>
            <name>WWZ</name>
            <offer date="2023-03-02">
                <postalcode>6300</postalcode>
                <price>12</price>
            </offer>
            <offer date="2023-03-02">
                <postalcode>6400</postalcode>
                <price>14</price>
            </offer>
            <offer date="2023-03-02">
                <postalcode>6200</postalcode>
                <price>2</price>
            </offer>
        </plant>
        <plant>
            <name>EWZ</name>
            <offer date="2023-03-02">
                <postalcode>8300</postalcode>
                <price>12</price>
            </offer>
            <offer date="2023-03-02">
                <postalcode>8400</postalcode>
                <price>14</price>
            </offer>
            <offer date="2023-03-02">
                <postalcode>8200</postalcode>
                <price>2</price>
            </offer>
        </plant>
    </energie-plant>
</energie-data>
